In [9]:
l = [234,567,856,985,-876]

In [10]:
l

[234, 567, 856, 985, -876]

In [12]:
import numpy as np


In [12]:
a = np.array(l)

In [14]:
a

array([ 234,  567,  856,  985, -876])

In [16]:
b = np.array(['12','13','34.6','67'],
             dtype='<U32')

In [17]:
print(b)

['12' '13' '34.6' '67']


In [18]:
l.pop()

-876

In [19]:
l

[234, 567, 856, 985]

In [20]:
a.mean()

353.19999999999999

In [21]:
l

[234, 567, 856, 985]

In [22]:
l[1:]

[567, 856, 985]

In [23]:
l[0:2]

[234, 567]

In [24]:
l[::2]

[234, 856]

In [25]:
#-----

In [26]:
a

array([ 234,  567,  856,  985, -876])

In [27]:
a[2:]

array([ 856,  985, -876])

In [28]:
b = a[2:4]

In [29]:
b

array([856, 985])

In [30]:
b[0]

856

In [31]:
b[:]

array([856, 985])

In [32]:
b[:] = 111

In [33]:
b

array([111, 111])

In [34]:
a

array([ 234,  567,  111,  111, -876])

In [35]:
c = a.copy()

In [36]:
c

array([ 234,  567,  111,  111, -876])

In [39]:
c[0] = 0

In [40]:
c

array([   0,  567,  111,  111, -876])

In [41]:
a

array([ 234,  567,  111,  111, -876])

In [4]:
b=np.array([1,2,3,45,6])

In [5]:
b

array([ 1,  2,  3, 45,  6])

---

In [14]:
import scrapy

In [2]:
import array as arr

In [6]:
v=arr.array('i',[56,78,90,34,12])

In [7]:
v

array('i', [56, 78, 90, 34, 12])

In [8]:
v.pop()

12

In [9]:
v

array('i', [56, 78, 90, 34])

In [16]:
x=np.array([45,78,90,34,12,78,'abc'])

In [17]:
x

array(['45', '78', '90', '34', '12', '78', 'abc'], dtype='<U11')

In [18]:
print(x)

['45' '78' '90' '34' '12' '78' 'abc']
